# 种子配置
seed:
  35

# 数据集配置
dataset:
  name: 'cityscapes'
  mode: 'csg'        # origin / foreground / background / csg / nda
  csg_mode: 'both'   # foreground / background / both

# 模型配置
model:
  name: 'segformer'
  from_scratch: false
  checkpoint_path: '../models/segformer_mit-b3_8x1_1024x1024_160k_cityscapes_20211206_224823-a8f8a177.pth'

# 训练超参数
train:
  num_epochs: 20
  batch_size: 2
  lr_backbone: 1.0e-05
  lr_classifier: 1.0e-04
  bn_frozen: false

# 损失函数权重
loss:
  alpha: 0.0025
  beta: 1.0

# 优化器
optimizer:
  name: "SGD" # Adam or SGD
  beta: (0.9, 0.999)
  weight_decay: 0.0001
  momentum: 0.9

# 学习率预热
warmup:
  enabled: true
  iters: 1000
  factor: 0.01

# 日志与输出
logging:
  date: "_1_29_2026"
  info: "_BL+CSG+CL+both_A0.0025B1_"
  root: "../log/"