# 种子配置
seed:
  35

# 数据集配置
dataset:
  name: 'cityscapes'
  mode: 'csg'        # origin / foreground / background / csg / nda
  csg_mode: 'both'   # foreground / background / both

# 模型配置
model:
  name: 'segformer'
  from_scratch: false
  checkpoint_path: '../models/segformer_bl.bin'

# 训练超参数
train:
  num_epochs: 50
  batch_size: 2
  lr_backbone: 6.0e-6
  lr_classifier: 6.0e-5
  bn_frozen: false

# 损失函数权重
loss:
  alpha: 10.0
  beta: 1.0

# 优化器
optimizer:
  name: "AdamW" # AdamW or SGD
  beta: (0.9, 0.999)
  weight_decay: 0.01
  momentum: 0.9

# 学习率预热
warmup:
  enabled: true
  iters: 1500
  factor: 0.001

# 日志与输出
logging:
  date: "_1_31_2026"
  info: "_BL+CSG+CL+both_A0.01B1_lrX100_LRdiff_"
  root: "../log/"