# 种子配置
seed:
  35

# 数据集配置
dataset:
  name: 'cityscapes'
<<<<<<< HEAD
  mode: 'csg'        # origin / foreground / background / csg / nda
  csg_mode: 'both'   # foreground / background / both
=======
  mode: 'csg'        # origin / csg
>>>>>>> master

# 模型配置
model:
  name: 'segformer'
  from_scratch: false
  checkpoint_path: '../models/segformer_bl.bin'

# 训练超参数
train:
<<<<<<< HEAD
  num_epochs: 5
=======
  num_epochs: 30
>>>>>>> master
  batch_size: 2
  lr_backbone: 6.0e-6
  lr_classifier: 6.0e-5
  bn_frozen: true

# 损失函数权重
loss:
  alpha: 10.0
  beta: 1.0

# 优化器
optimizer:
  name: "AdamW" # AdamW or SGD
  betas:
   - 0.9
   - 0.999
  weight_decay: 0.01
  momentum: 0.9

# 学习率预热
warmup:
  enabled: true
  iters: 1500
  factor: 0.001

# 日志与输出
logging:
<<<<<<< HEAD
  date: "_2_1_2026"
  info: "_ONLYFORTEST_"
=======
  date: "_2_4_2026"
  info: "_BL+CSG+CL+WeightedErased1_"
>>>>>>> master
  root: "../log/"